# TODO

# We use Maven version 3.6.3 for the build, with JDK 11.

# Run restore.sh and then build.sh - you'll need to make
# the files executable first with chmod +x <filename>.

# Build output is a single JAR file:
#  /usr/src/api/target/products-api-0.1.0.jar

# The app should run on OpenJDK 11.0.12, it can use a minimal OS. 

# We need to set two environment variables - 
# JRE_VERSION and APP_VERSION. 

# The startup command needs to run the JAR file from the build:
#  java -jar products-api-0.1.0.jar