services:
  rng-api:
    image: dockerfundamentals/rng-api:21.05
    environment:
      - Rng__FailAfter__Enabled=true
      - Rng__FailAfter__CallCount=3
      - Rng__FailAfter__Action=Exit
    networks:
      - app-net

  rng-web:
    image: dockerfundamentals/rng-web:21.05
    environment:
      - Logging__LogLevel__Default=Debug
      - RngApi__Url=http://rng-api/rng
    ports:
      - "8088:80"
    networks:
      - app-net

networks:
  app-net:
