# TODO

# We use .NET Core SDK version 3.1 for the build.

# Run restore.sh and then build.sh - you'll need to make
# the files executable first with chmod +x <filename>.

# Build output is in the folder:
#  /out

# The app should run using a .NET Core ASP.NET 3.1 image, with a minimal OS.
 
# We need to set four environment variables - 
# DOTNET_VERSION and APP_VERSION
# Widgetario__ProductsApi__Url set to "http://products-api/products"
# Widgetario__StockApi__Url set to "http://stock-api:8080/stock"

# The startup command needs to run the DLL  from the build:
#  dotnet Widgetario.Web.dll
