# TODO

# We use Postgres for the database, version 11.6 - it can use a minimal OS.

# There's an init script in this folder which populates the reference data:
#  init-products-db.sh

# Your base image should make it easy to run that script as part of the container startup.